### ISSUE TITLE
Bug: warnings when using the library about "androidTestApi" and "androidTestCompile" being used

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [objectbox/objectbox-java#375]
## Issue Basics
- ObjectBox version (are using the latest version?): *?*
1.4.1

- Reproducibility: *[occurred once only | occasionally without visible pattern | always]*
always

### Description
*Describe the situation in English in which you encounter the bug.*
Just create a project that uses the library via gradle. No need for code.
The bug is that the IDE will warn about having these lines in gradle, even though I don't have them.
They appear only when using this library.
Here's a sample project:
[MyApplication.zip](https://github.com/objectbox/objectbox-java/files/1757650/MyApplication.zip)

The warnings you get:

> Warning:Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
> It will be removed at the end of 2018
> Warning:Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
> It will be removed at the end of 2018

### Code
*Provide the code triggering the bug.
No need

### Logs & stackstraces
*Check if you have relevant logs and/or a stacktrace.
No need

## Entities
*Provide the code for entities related to the bug (shorten to relevant parts).*
None

## Misc
*Is there anything special about your app?
No

Did you find any workarounds to prevent the issue?*
No

**Comment by AndroidDeveloperLB** [comment]
In case this is an IDE/gradle issue, I've written about it here as well:

https://issuetracker.google.com/issues/73186248

**Comment by AndroidDeveloperLB** [comment]
If it's not available, why close this?

**Comment by greenrobot-team** [comment]
Closed because it is fixed (!= released), the fix will be released with the next update (likely 1.4.6). -ut

**Comment by AndroidDeveloperLB** [comment]
How could I verify it's fixed, if it's not released...
Therefore it doesn't make sense to close it. The issue still exists in all versions that are available.

**Comment by greenrobot-team** [comment]
Just re-open the issue or comment if the fix is not successful. See our comments and the milestone info to learn what release an issue was resolved in. This is how we handle issues, please adapt.
 -ut

**Comment by AndroidDeveloperLB** [comment]
@greenrobot-team I can't, because it's not available, and once it is available, I won't be notified about it. And even if I do get notified, how could I dig into all the issues to get here, if it's closed...
It should have been this way:
1. issue reported
2. issue confirmed (and if not, closed)
3. issue fixed
4. bug fixed published, including telling here that it's published.
5. anyone who subscribed to the bug report (me in this case) get notification and can check it back.
6. confirmation that it indeed got fixed, and can be closed.
